version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.0
  aws-s3: circleci/aws-s3@4.0

jobs:
  cloudformation-lint:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install cfn-lint
      - run:
          name: Validate templates
          command: cfn-lint templates/cloudformation/*

  terraform-lint:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Format and validate
          command: |
            cd templates/terraform
            terraform init -backend=false
            terraform fmt -recursive -check -diff
            terraform validate

workflows:
  version: 2

  publish:
    jobs:
      - cloudformation-lint
      - terraform-lint
      - aws-s3/sync:
          name: publish-resources-dev
          auth:
            - aws-cli/setup:
                aws_access_key_id: AWS_ACCESS_KEY_ID
                aws_secret_access_key: AWS_SECRET_ACCESS_KEY
                region: AWS_REGION
          context: aws-dev
          requires:
            - cloudformation-lint
            - terraform-lint
          filters:
            branches:
              only:
                - dev
          from: ./templates/
          to: s3://${PUBLIC_RESOURCES_BUCKET}
      - aws-s3/sync:
          name: publish-resources-prod
          auth:
            - aws-cli/setup:
                aws_access_key_id: AWS_ACCESS_KEY_ID
                aws_secret_access_key: AWS_SECRET_ACCESS_KEY
                region: AWS_REGION
          context: aws-prod
          requires:
            - cloudformation-lint
            - terraform-lint
          filters:
            branches:
              only:
                - main
          from: ./templates/
          to: s3://${PUBLIC_RESOURCES_BUCKET}